#!/usr/bin/env python3
"""
Comprehensive SEO Fix Script for streamdeutschland.de
Fixes: long titles, meta description lengths, SearchAction schema,
hreflang coverage, canonical on plan pages, sitemap
"""
import re, glob, os, sys

BASE_URL = "https://streamdeutschland.de"

# ============================================================
# TITLE SHORTENER MAP
# Pattern: current title (>60 chars) → fixed title (≤60 chars)
# ============================================================
TITLE_FIXES = {
    "best-iptv.html":              "Best IPTV Germany 2026 – Top Service | StreamDeutschland",
    "beste-iptv-app.html":         "Beste IPTV App 2026 – Vergleich & Test | StreamDeutschland",
    "bester-iptv-anbieter.html":   "Bester IPTV Anbieter 2026 – Test | StreamDeutschland",
    "bester-iptv-player.html":     "Bester IPTV Player 2026 – Vergleich | StreamDeutschland",
    "bestes-iptv.html":            "Bestes IPTV 2026 – Top-Anbieter Vergleich | StreamDE",
    "iptv-alle-sender.html":       "IPTV alle Sender 2026 – 50.000+ Kanäle | StreamDeutschland",
    "iptv-android-box.html":       "IPTV Android Box 2026 – Einrichten | StreamDeutschland",
    "iptv-android-player.html":    "IPTV Android Player 2026 – Einrichten | StreamDeutschland",
    "iptv-arabisch.html":          "Arabisches IPTV 2026 – MBC & Al Jazeera | StreamDeutschland",
    "iptv-augsburg.html":          "IPTV Augsburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-bielefeld.html":         "IPTV Bielefeld 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-braunschweig.html":      "IPTV Braunschweig 2026 – Bester Anbieter | StreamDE",
    "iptv-browser.html":           "IPTV im Browser 2026 – Chrome, Firefox | StreamDeutschland",
    "iptv-buffering.html":         "IPTV Buffering beheben 2026 – Tipps | StreamDeutschland",
    "iptv-catch-up.html":          "IPTV Catch-Up 2026 – Sendungen nachholen | StreamDE",
    "iptv-champions-league.html":  "IPTV Champions League 2026 – UCL live 4K | StreamDE",
    "iptv-chemnitz.html":          "IPTV Chemnitz 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-darmstadt.html":         "IPTV Darmstadt 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-duisburg.html":          "IPTV Duisburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-epg.html":               "IPTV EPG 2026 – Programmführer einrichten | StreamDE",
    "iptv-erfahrungen.html":       "IPTV Erfahrungen 2026 – Bewertungen | StreamDeutschland",
    "iptv-erlangen.html":          "IPTV Erlangen 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-extreme.html":           "IPTV Extreme 2026 – Xtream Codes Player | StreamDE",
    "iptv-fire-stick-4k.html":     "IPTV Fire TV Stick 4K 2026 – Anleitung | StreamDE",
    "iptv-formuler.html":          "IPTV Formuler Box 2026 – Einrichten | StreamDeutschland",
    "iptv-forum.html":             "IPTV Forum 2026 – Was Nutzer empfehlen | StreamDE",
    "iptv-freiburg.html":          "IPTV Freiburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-gelsenkirchen.html":     "IPTV Gelsenkirchen 2026 – Bester Anbieter | StreamDE",
    "iptv-german.html":            "German IPTV 2026 – Watch German TV Online | StreamDE",
    "iptv-germany.html":           "IPTV Germany 2026 – German Subscription | StreamDE",
    "iptv-goettingen.html":        "IPTV Göttingen 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-gratis-testen.html":     "IPTV gratis testen 2026 – kostenlos | StreamDeutschland",
    "iptv-guenstig.html":          "Günstiges IPTV 2026 – ab 9€/Monat | StreamDeutschland",
    "iptv-halle.html":             "IPTV Halle (Saale) 2026 – Bester Anbieter | StreamDE",
    "iptv-hd.html":                "IPTV HD 2026 – alle Sender in High Definition | StreamDE",
    "iptv-heidelberg.html":        "IPTV Heidelberg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-heilbronn.html":         "IPTV Heilbronn 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-hisense.html":           "IPTV Hisense Smart TV 2026 – Einrichten | StreamDE",
    "iptv-huawei.html":            "IPTV Huawei 2026 – ohne Google Play | StreamDeutschland",
    "iptv-ingolstadt.html":        "IPTV Ingolstadt 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-innsbruck.html":         "IPTV Innsbruck 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-karlsruhe.html":         "IPTV Karlsruhe 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-kinder.html":            "IPTV Kinder 2026 – KiKA, Disney & mehr | StreamDE",
    "iptv-kostenlos.html":         "IPTV kostenlos 2026 – Gratis vs. Abo | StreamDeutschland",
    "iptv-leverkusen.html":        "IPTV Leverkusen 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-linie.html":             "IPTV Linie 2026 – Line testen & kaufen | StreamDE",
    "iptv-live-tv.html":           "IPTV Live TV 2026 – Fernsehen über Internet | StreamDE",
    "iptv-ludwigshafen.html":      "IPTV Ludwigshafen 2026 – Bester Anbieter | StreamDE",
    "iptv-m3u-listen.html":        "IPTV M3U Listen Deutsch 2026 – Playlisten | StreamDE",
    "iptv-magdeburg.html":         "IPTV Magdeburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-mannheim.html":          "IPTV Mannheim 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-mecool.html":            "IPTV Mecool Box 2026 – Einrichten | StreamDeutschland",
    "iptv-moenchengladbach.html":  "IPTV Mönchengladbach 2026 – Anbieter | StreamDE",
    "iptv-muelheim.html":          "IPTV Mülheim Ruhr 2026 – Bester Anbieter | StreamDE",
    "iptv-nvidia-shield.html":     "IPTV Nvidia Shield 2026 – Einrichten | StreamDeutschland",
    "iptv-oberhausen.html":        "IPTV Oberhausen 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-oesterreich.html":       "IPTV Österreich 2026 – ORF & mehr | StreamDeutschland",
    "iptv-offenbach.html":         "IPTV Offenbach 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-ohne-receiver.html":     "IPTV ohne Receiver 2026 – ohne Schüssel | StreamDE",
    "iptv-oldenburg.html":         "IPTV Oldenburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-osnabrueck.html":        "IPTV Osnabrück 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-paderborn.html":         "IPTV Paderborn 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-panasonic.html":         "IPTV Panasonic Smart TV 2026 – Einrichten | StreamDE",
    "iptv-paypal.html":            "IPTV mit PayPal kaufen 2026 – sicher | StreamDeutschland",
    "iptv-pforzheim.html":         "IPTV Pforzheim 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-philips.html":           "IPTV Philips Smart TV 2026 – Einrichten | StreamDE",
    "iptv-playlist-deutsch.html":  "IPTV Playlist Deutsch 2026 – M3U & Sender | StreamDE",
    "iptv-playstation.html":       "IPTV PlayStation PS4/PS5 2026 – Einrichten | StreamDE",
    "iptv-polnisch.html":          "Polnisches IPTV 2026 – TVP & Polsat | StreamDeutschland",
    "iptv-raspberry-pi.html":      "IPTV Raspberry Pi 2026 – Einrichten | StreamDeutschland",
    "iptv-regensburg.html":        "IPTV Regensburg 2026 – Bester Anbieter | StreamDE",
    "iptv-remscheid.html":         "IPTV Remscheid 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-reseller.html":          "IPTV Reseller Germany 2026 – Partner | StreamDeutschland",
    "iptv-russisch.html":          "Russisches IPTV 2026 – Perviy Kanal & RTR | StreamDE",
    "iptv-saarbruecken.html":      "IPTV Saarbrücken 2026 – Bester Anbieter | StreamDE",
    "iptv-salzburg.html":          "IPTV Salzburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-schweiz.html":           "IPTV Schweiz 2026 – SRF & 50.000+ Sender | StreamDE",
    "iptv-server.html":            "IPTV Server 2026 – stabile Server | StreamDeutschland",
    "iptv-smarters.html":          "IPTV Smarters 2026 – Einrichtung | StreamDeutschland",
    "iptv-solingen.html":          "IPTV Solingen 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-sony.html":              "IPTV Sony Bravia 2026 – Einrichten | StreamDeutschland",
    "iptv-sport-sender.html":      "IPTV Sport Sender 2026 – Bundesliga & CL | StreamDE",
    "iptv-statt-kabel.html":       "IPTV statt Kabel 2026 – Vergleich | StreamDeutschland",
    "iptv-subscription.html":      "IPTV Subscription Germany 2026 – from €9 | StreamDE",
    "iptv-tablet.html":            "IPTV Tablet Android & iPad 2026 – Einrichten | StreamDE",
    "iptv-telekom.html":           "IPTV vs Telekom MagentaTV 2026 – Vergleich | StreamDE",
    "iptv-testline.html":          "IPTV Testline 2026 – kostenlose Linie | StreamDeutschland",
    "iptv-tuerkisch.html":         "Türkisches IPTV 2026 – TRT & Show TV | StreamDeutschland",
    "iptv-vod.html":               "IPTV VOD 2026 – Video on Demand | StreamDeutschland",
    "iptv-vodafone.html":          "IPTV vs Vodafone TV 2026 – Vergleich | StreamDE",
    "iptv-vs-amazon-prime.html":   "IPTV vs Amazon Prime 2026 – Vergleich | StreamDE",
    "iptv-vs-netflix.html":        "IPTV vs Netflix 2026 – Unterschied | StreamDeutschland",
    "iptv-wiesbaden.html":         "IPTV Wiesbaden 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-winterthur.html":        "IPTV Winterthur 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-wolfsburg.html":         "IPTV Wolfsburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-wuerzburg.html":         "IPTV Würzburg 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-wuppertal.html":         "IPTV Wuppertal 2026 – Bester Anbieter | StreamDeutschland",
    "iptv-xbox.html":              "IPTV Xbox One/Series X 2026 – Einrichten | StreamDE",
    "iptv-xiaomi.html":            "IPTV Xiaomi Mi Box 2026 – Einrichten | StreamDE",
    "iptv-xtream-codes.html":      "Xtream Codes IPTV 2026 – Einrichtung | StreamDE",
    "smart-one-iptv.html":         "Smart One IPTV 2026 – Alternative | StreamDeutschland",
    "what-is-iptv.html":           "What is IPTV? Explained 2026 | StreamDeutschland",
    "bestes-iptv.html":            "Bestes IPTV 2026 – Top-Anbieter im Test | StreamDE",
}

# Verify all fixes are ≤60 chars
print("=== TITLE LENGTH VERIFICATION ===")
for fn, title in TITLE_FIXES.items():
    if len(title) > 60:
        print(f"STILL TOO LONG [{len(title)}]: {fn} => {title}")
print("Done verifying")

